### PR TITLE
feat: update standards

### PR DESCRIPTION
**Pull request by abenevaut**
Hello Hello!
Nice to meet this super cool project!

This PR depends on: https://github.com/mishterk/wp-tailwindcss-theme-boilerplate/pull/14 (<= should be merged first)

This PR contains some improvements that I consider useful to lead this project towards a good evolution of its community.
I am taker of all the returns:
- that you will not wish to see merged (to withdraw them)
- all the evolutions which will seem useful to you.

I await your feedback ;-)

### Added
- Installed composer and phpcs (with coding standard PSR12); The composer introduction will drive to the use of `composer create-project mishterk/wp-tailwindcss-theme-boilerplate my-template` for users, to do not clone this repository (that can conduct to do repository mistakes); Please, if this feature is OK for you, register the repository to [packagist](https://packagist.org) with name `mishterk/wp-tailwindcss-theme-boilerplate`
- Configured dependabot for composer vendors
- Added CI workflows with github actions to validate PHP code style & the capacity to correctly `npm run prod` for each PR

### Changed
- Renamed AssetResolver to Mix => This project manage only one kind of assets resolution and strongly linked, seem to me more appropriate
- Fixed code style, updated to CS PSR12, for `app/*.php`, `includes/*.php` files
- Moved all files `*-example.*` to `*.*.example` to look like Laravel & Bedrock WP projects
- Renamed `assets` to `resources` to look like Laravel project; Express better (in my opinion) the fact that these are files for development
- Renamed `build` to `assets` to look like Laravel project; Better express (in my opinion) the fact that these are files for production

### CODE REVIEW

**Comment by Aetles** [comment]
Is removing `style.css` really wise? According to the Theme Handbook it is a [required file for all WordPress themes](https://developer.wordpress.org/themes/basics/main-stylesheet-style-css/) and it contains the information that is needed for WordPress to recognize the theme:

> In order for WordPress to recognize the set of theme template files as a valid theme, the style.css file needs to be located in the root directory of your theme, not a subdirectory.

**Comment by abenevaut** [comment]
Thanks for your review. I did not have this point in mind, I restore the file.

**Comment by mishterk** [comment]
Hi @abenevaut, thanks for the PR — glad you like the boilerplate. 

Whilst I can appreciate what you are going for in your PR, I think these modifications might be best suited as a fork. 

The style.css file is essential for WordPress themes as has already been pointed out, so that definitely needs to stay. 

As much as a I love Laravel (like, a lot) this isn't a Laravel or a Bedrock project so I'm not interested in mimicking those. When I build WordPress themes, I prefer to keep them as close to WordPress as possible. Any modifications that make a WordPress site look more like Laravel are generally confusing to other WordPress developers as it isn't common for WordPress devs to use Laravel or Bedrock. I'd like to keep this as simple as possible. 

IMO, Composer doesn't belong in here by default. I do use Composer a lot but it's not a default for WordPress theme dev so I leave it up to the end user to decide whether they wish to add it after cloning the repo. 

The change from AssetResolver to Mix is an interesting suggestion but I'd prefer not to tie it directly to Mix as, theoretically, any other asset build process could be supported. I suppose we should probably remove the hardcoded import of Mix's manifest and make that configurable but outside of that, it's relatively independent of build process, no?

**Comment by abenevaut** [comment]
I complety understand all yours points and your vision. Thanks you to getting me a complete answer. 
I will remain under observation on this repo to see how you are progressing ;-) Feel free to ask me if necessary.

**Pull request closed without merging**
